#!/bin/bash

PATH="/sbin:/usr/sbin:/bin:/usr/bin:$PATH"

board=bananapi-m5

kernel_version=$(pacman -Qi linux | grep Version | cut -d: -f2 | xargs)
kernel_major=$(echo ${kernel_version} | cut -d. -f1)
kernel_minor=$(echo ${kernel_version} | cut -d. -f2)

boot_ini=""
boot_ini_version=""
if [ $kernel_major -gt 4 ]; then
    boot_ini=/usr/share/uboot-${board}/boot.mainline.ini
    boot_ini_version="mainline"
else
    boot_ini=/usr/share/uboot-${board}/boot.bananapi.ini
    boot_ini_version="bananapi"
fi

if [ -e /boot/boot.ini ]; then
    if ! grep "KERNEL: ${boot_ini_version}" /boot/boot.ini > /dev/null ; then
        mv /boot/boot.ini "/boot/boot.ini.$(date +"%s")"
        cp $boot_ini /boot/boot.ini
    fi
else
    cp $boot_ini /boot/boot.ini
fi

model=""
if [ -e /sys/devices/soc0/machine ]; then
  model="$(cat /sys/devices/soc0/machine | sed "s/Bananapi //g")"
elif [ -e /sys/firmware/devicetree/base/model ]; then
  model="$(cat /sys/firmware/devicetree/base/model | sed "s/Bananapi //g")"
fi

if [ "$model" = "BPI-M2-Pro" ]; then
    if [ -e /boot/dtbs/amlogic/meson64_bananapi_m2_pro.dtb ]; then
        sed -i "s/\/dtbs\/amlogic\/meson-sm1-bananapi-m2-pro\.dtb/\/dtbs\/amlogic\/meson64_bananapi_m2_pro\.dtb/g" \
            /boot/boot.ini
    elif [ -e /boot/dtbs/amlogic/meson-sm1-bananapi-m2-pro.dtb ]; then
        sed -i "s/\/dtbs\/amlogic\/meson64_bananapi_m2_pro\.dtb/\/dtbs\/amlogic\/meson-sm1-bananapi-m2-pro\.dtb/g" \
            /boot/boot.ini
    elif [ -e /boot/dtbs/amlogic/meson64_bananapi_m5.dtb ]; then
        sed -i "s/\/dtbs\/amlogic\/meson-sm1-bananapi-m2-pro\.dtb/\/dtbs\/amlogic\/meson64_bananapi_m5\.dtb/g" \
            /boot/boot.ini
        sed -i "s/\/dtbs\/amlogic\/meson-sm1-bananapi-m5\.dtb/\/dtbs\/amlogic\/meson64_bananapi_m5\.dtb/g" \
            /boot/boot.ini
        echo "Warning: Using bananapi-m5 dtb on bananapi-m2-pro"
    elif [ -e /boot/dtbs/amlogic/meson-sm1-bananapi-m5.dtb ]; then
        sed -i "s/\/dtbs\/amlogic\/meson64_bananapi_m2_pro\.dtb/\/dtbs\/amlogic\/meson-sm1-bananapi-m5\.dtb/g" \
            /boot/boot.ini
        sed -i "s/\/dtbs\/amlogic\/meson64_bananapi_m5\.dtb/\/dtbs\/amlogic\/meson-sm1-bananapi-m5\.dtb/g" \
            /boot/boot.ini
        echo "Warning: Using bananapi-m5 dtb on bananapi-m2-pro"
    else
        echo "Error: The kernel you installed doesn't seems to support the bananapi-m2-pro"
    fi
else
    if [ -e /boot/dtbs/amlogic/meson64_bananapi_m5.dtb ]; then
        sed -i "s/\/dtbs\/amlogic\/meson-sm1-bananapi-m5\.dtb/\/dtbs\/amlogic\/meson64_bananapi_m5\.dtb/g" \
            /boot/boot.ini
    elif [ -e /boot/dtbs/amlogic/meson-sm1-bananapi-m5.dtb ]; then
        sed -i "s/\/dtbs\/amlogic\/meson64_bananapi_m5\.dtb/\/dtbs\/amlogic\/meson-sm1-bananapi-m5\.dtb/g" \
            /boot/boot.ini
    else
        echo "Error: The kernel you installed doesn't seems to support the bananapi-m5"
    fi
fi

# Add proper UUID to boot.ini
major=$(mountpoint -d / | cut -f 1 -d ':')
minor=$(mountpoint -d / | cut -f 2 -d ':')
device=$(cat /proc/partitions | awk {'if ($1 == "'${major}'" && $2 == "'${minor}'") print $4 '})
device_uuid=$(lsblk -o uuid,name | grep ${device} | awk "{print \$1}")

sed -i "s/root=\/dev\/mmcblk\${devno}p2/root=UUID=${device_uuid}/g" \
    /boot/boot.ini
